### PR TITLE
Issuance: Apply user given precision

### LINKED ISSUE #120: Fix usage of precision for issuance amount
At the moment the usage of the precision specified in the `NewTxIssuance` factory function is wrong in the sense that it should be used as a factor rather than divider in the formula. This should be:
```
assetAmount := arg.AssetAmount * 10^(p) # where p = precision = [0,8]
```

### PR DESCRIPTION
**Pull request by altafan**
This closes #120.

@tiero please, review this

### CODE REVIEW

File: transaction/issuance.go [hunk 1]
```diff
@@ -170,21 +170,21 @@ func (issuance *TxIssuanceExtended) GenerateReissuanceToken(flag uint) ([]byte,
 	return token[:], nil
 }
 
-func toConfidentialAssetAmount(assetAmount float64, precision uint) ([]byte, error) {
-	amount := uint64(assetAmount * math.Pow10(int(8-precision)))
+func toConfidentialAssetAmount(assetAmount uint64, precision uint) ([]byte, error) {
+	amount := assetAmount * uint64(math.Pow10(int(8+precision)))
```
Comment (tiero) [inline transaction/issuance.go:174]: Just Pow10(precision)
