### PR TITLE
AddInReissuance various fix and improvements

### LINKED ISSUE #213: [PSET v2] allow issuance and reissuance pset with confidential & unconfidential addresses
similar to: https://github.com/vulpemventures/liquidjs-lib/issues/82

### PR DESCRIPTION
**Pull request by louisinger**
* various fixes in AddInReissuance
* `AddInReissuance` does not add the input anymore (choose a valid input)
* `AddInIssuance` now needs an input index
* add a blinded reissuance integration test using psetv2 pkg

it closes #213 

@altafan please review

### CODE REVIEW

File: psetv2/input.go [hunk 1]
```diff
@@ -205,9 +205,6 @@ func (i *Input) HasIssuanceBlinded() bool {
 }
 
 func (i *Input) HasReissuance() bool {
-	if len(i.IssuanceBlindingNonce) > 0 {
-		return false
-	}
 	return !bytes.Equal(i.IssuanceBlindingNonce, transaction.Zero[:])
```
Comment (altafan) [inline psetv2/input.go:208]: let's keep the original check and fix it. the condition should be `<=` not `>`. If no blinding nonce is set the inputs hasn't got any reissuance.

**Review by altafan — APPROVED** [review]

File: psetv2/updater.go [hunk 2]
```diff
@@ -483,81 +463,81 @@ func (arg AddInReissuanceArgs) areAddressesConfidential() bool {
...
-		)
+	if err := arg.validate(); err != nil {
+		return err
 	}
 
 	p := u.Pset.Copy()
 
-	// add input
-	if err := p.addInput(arg.TokenPrevOut.toPartialInput()); err != nil {
+	entropy, err := hex.DecodeString(arg.Entropy)
```
Comment (altafan) [inline psetv2/updater.go:477]: we should make sure that entropy is correct in args validation function rather than returning an error here. If the entropy is not an hex or its not exactly `32`  bytes then we return an `invalid issuance entropy` error message

File: psetv2/updater.go [hunk 3]
```diff
@@ -483,81 +463,81 @@ func (arg AddInReissuanceArgs) areAddressesConfidential() bool {
...
-			return err
-		}
-	}
-
-	entropy, _ := hex.DecodeString(arg.Entropy)
 	entropy = elementsutil.ReverseBytes(entropy)
 	issuance := transaction.NewTxIssuanceFromEntropy(entropy)
 
-	rawAsset, _ := issuance.GenerateAsset()
+	rawAsset, err := issuance.GenerateAsset()
```
Comment (altafan) [inline psetv2/updater.go:484]: same here

File: psetv2/updater.go [hunk 4]
```diff
@@ -483,81 +463,81 @@ func (arg AddInReissuanceArgs) areAddressesConfidential() bool {
...
+	if err != nil {
+		return err
+	}
 	rawAsset = append([]byte{0x01}, rawAsset...)
 	reissuedAsset := elementsutil.AssetHashFromBytes(rawAsset)
-	addr, _ := address.FromConfidential(arg.AssetAddress)
+	addr, err := address.FromConfidential(arg.AssetAddress)
```
Comment (altafan) [inline psetv2/updater.go:490]: and here

File: psetv2/updater.go [hunk 5]
```diff
@@ -483,81 +463,81 @@ func (arg AddInReissuanceArgs) areAddressesConfidential() bool {
...
 	if out.NeedsBlinding() {
-		out.BlinderIndex = arg.TokenPrevOut.TxIndex
+		out.BlinderIndex = uint32(inputIndex)
 	}
 	if err := p.addOutput(out); err != nil {
 		return err
 	}
 
-	rawAsset, _ = issuance.GenerateReissuanceToken(
+	rawAsset, err = issuance.GenerateReissuanceToken(
```
Comment (altafan) [inline psetv2/updater.go:509]: and also here

File: psetv2/updater.go [hunk 6]
```diff
@@ -483,81 +463,81 @@ func (arg AddInReissuanceArgs) areAddressesConfidential() bool {
...
 		ConfidentialReissuanceTokenFlag,
 	)
+	if err != nil {
+		return err
+	}
+
 	rawAsset = append([]byte{0x01}, rawAsset...)
 	tokenAsset := elementsutil.AssetHashFromBytes(rawAsset)
-	addr, _ = address.FromConfidential(arg.TokenAddress)
+	addr, err = address.FromConfidential(arg.TokenAddress)
```
Comment (altafan) [inline psetv2/updater.go:518]: even here

**Comment by altafan** [comment]
@louisinger since #211 got merged, we can now update the `BlindOutputs()` function of the zkp generator and remove the `issuanceBlidningArgs` argument.

Since the spec states that in case an input has an issuance, it has to consider to be blinded if the blinded issuance flag is true OR UNDEFINED, I think it's worth adding a utility method `IsIssuanceBlinded()` to the partial input that makes sure to always return the correct value following the spec recommendation.

**Review by altafan — CHANGES_REQUESTED** [review]
sync with master and add suggested changes

**Comment by louisinger** [comment]
add also fix to: #213 
+ several new tests cases

File: address/address.go [hunk 7]
```diff
@@ -185,7 +185,8 @@ func ToBech32(bc *Bech32) (string, error) {
 }
 
 // FromBase58Confidential decodes a confidenail address that was base58 encoded
-//  and verifies the checksum.
+//
+//	and verifies the checksum.
```
Comment (altafan) [inline address/address.go:189]: can you revert this? I guess your purpose was to remove the extra leading space.

File: pset/updater.go [hunk 8]
```diff
@@ -539,16 +539,17 @@ func (p *Updater) AddIssuance(arg AddIssuanceArgs) error {
...
-//		PrevOutIndex: the prevout index of the token that will be added as input to the tx
-//		PrevOutBlinder: the asset blinder used to blind the prevout token
-//		WitnessUtxo: the prevout token in case it is a witness one
-//		NonWitnessUtxo: the prevout tx that include the token output in case it is a non witness one
-//		Entropy: the entropy used to generate token and asset
-//		AssetAmount: the amount of asset to re-issue
-//		TokenAmount: the same unblinded amount of the prevout token
-//		AssetAddress: the destination address of the re-issuing asset
-//		TokenAddress: the destination address of the re-issuance token
+//
```
Comment (altafan) [inline pset/updater.go:542]: remove empty line

File: psetv2/updater.go [hunk 9]
```diff
@@ -378,21 +380,19 @@ func (u *Updater) AddInIssuance(arg AddInIssuanceArgs) error {
...
-//		PrevOutIndex: the prevout index of the token that will be added as input to the tx
-//		PrevOutBlinder: the asset blinder used to blind the prevout token
-//		WitnessUtxo: the prevout token in case it is a witness one
-//		NonWitnessUtxo: the prevout tx that include the token output in case it is a non-witness one
-//		Entropy: the entropy used to generate token and asset
-//		AssetAmount: the amount of asset to re-issue
-//		TokenAmount: the same unblinded amount of the prevout token
-//		AssetAddress: the destination address of the re-issuing asset
-//		TokenAddress: the destination address of the re-issuance token
+//
```
Comment (altafan) [inline psetv2/updater.go:383]: remove empty line

File: psetv2/updater.go [hunk 10]
```diff
@@ -539,25 +485,29 @@ func (u *Updater) AddInReissuance(arg AddInReissuanceArgs) error {
...
-		Script:       addr.Script,
-		BlindingKey:  addr.BlindingKey,
-		BlinderIndex: uint32(inputIndex),
+		Asset:       tokenAsset,
+		Amount:      arg.TokenAmount,
+		Script:      tokenScript,
+		BlindingKey: tokenBlindingKey,
+	}
+	if tokenBlindingKey != nil {
+		tokenOut.BlinderIndex = uint32(inputIndex)
```
Comment (altafan) [inline psetv2/updater.go:498]: not needed?

File: psetv2/updater.go [hunk 11]
```diff
@@ -249,52 +249,50 @@ func (arg AddInIssuanceArgs) validate() error {
...
+	return parseAddress(arg.AssetAddress)
+}
+
 func (arg AddInIssuanceArgs) parseTokenAddress() ([]byte, []byte) {
-	script, _ := address.ToOutputScript(arg.TokenAddress)
-	isConf, _ := address.IsConfidential(arg.TokenAddress)
-	if !isConf {
-		return script, nil
+	return parseAddress(arg.TokenAddress)
+}
```
Comment (altafan) [inline psetv2/updater.go:279]: either we remove these or add also for reissuance args, but let's fix this code inconsistency.

File: psetv2/updater.go (hunk 10 above)
Comment (louisinger) [reply psetv2/updater.go:498]: golang is complaining, inputIndex is an `int` whereas blinderIndex is an `uint32`

Comment (altafan) [reply psetv2/updater.go:502]: no i mean, we already take care of this [here](https://github.com/vulpemventures/go-elements/blob/78befafcb2f10aec4031aa10df580caad9c68ecd/psetv2/updater.go#L480-L482), therefore this is not needed.

Comment (altafan) [reply psetv2/updater.go:502]: remove this if block and it's good to be merged

File: psetv2/updater.go [hunk 12]
```diff
@@ -458,77 +428,57 @@ func (arg AddInReissuanceArgs) validate() error {
...
-		Amount:       arg.AssetAmount,
-		Script:       addr.Script,
-		BlindingKey:  addr.BlindingKey,
-		BlinderIndex: uint32(inputIndex),
+		Asset:       reissuedAsset,
+		Amount:      arg.AssetAmount,
+		Script:      script,
+		BlindingKey: blindingKey,
 	}
+	if blindingKey != nil {
```
Comment (altafan) [inline psetv2/updater.go:475]:
```suggestion
	if reissuanceOut.NeedsBlinding() {
```

File: psetv2/updater.go [hunk 13]
```diff
@@ -458,77 +428,57 @@ func (arg AddInReissuanceArgs) validate() error {
...
-		BlindingKey:  addr.BlindingKey,
-		BlinderIndex: uint32(inputIndex),
+		Asset:       reissuedAsset,
+		Amount:      arg.AssetAmount,
+		Script:      script,
+		BlindingKey: blindingKey,
 	}
+	if reissuanceOut.NeedsBlinding() {
+		reissuanceOut.BlinderIndex = uint32(inputIndex)
+	}
```
Comment (altafan) [inline psetv2/updater.go:477]:
```suggestion
```

**Review by altafan — APPROVED** [review]
